**Goal** : Convert `disregions.txt` to `disregionsB.csv`

In [1]:
# 0. Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 1. Path to file
# Input file
source_path = "/u/mdmc/enyanduk/internship_areasciencepark/Data/dpcfam/dpcfam_b/zenodo_unzipped_folders/B_metaclusters_xml/mc_info_from_xml/disregions.txt"
# Output file
target_path = "/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/DPCFamB/"

In [3]:
# Type of file ?
with open(source_path, "r",encoding="utf-8") as f:
  print(repr(f.readline()))

'3 0.301511\n'

`Oberservation` : It's a `spaces`-separated file.

In [4]:
# Convert to a dataframe
df = pd.read_csv(source_path, sep=r"\s+",header=None, names=["MCID","%DIS"], skip_blank_lines=True)
df["MCID"] = df["MCID"].astype(int)
df = df.sort_values(by="MCID").reset_index(drop=True)
df.head()

   MCID      %DIS
0     3  0.301511
1     5  0.075087
2     7  0.000958
3    11  0.156112
4    17  0.318756

In [5]:
# Infos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34556 entries, 0 to 34555
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MCID    34556 non-null  int64
 1   %DIS    34556 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 540.1 KB

In [6]:
# Statistics
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MCID,34556.0,181682.752633,144959.400413,3.0,53345.000000,147510.000000,292932.250000,504492.0
%DIS,34556.0,0.160469,0.244172,0.0,0.008285,0.042036,0.192014,1.0

In [7]:
# Save to csv 
final_target = target_path + "disregionsB.csv"
df.to_csv(final_target, index=False)