In [1]:
# Imports
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import data_profiling # updated version of pandas-profiling
from data_profiling import ProfileReport

In [2]:
# DPCFam Standard Mcs Sequences
df1 = pd.read_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/dpcfam_sequences.csv")
df1.head()

,mcid,protein_id,seq_range,seq_length,aa_seq
0,MC82027,E8W9U6,2-131,130,ILLLSTSDTDLLSARAAQGPVSYRYANPSRLSLDALPQLLEGTDLV...
1,MC82027,I7DYJ9,1-143,143,MHVVFRESHGLDESDTPQDLGQTPADLVVLSFSDSDLGAFAAGWHR...
2,MC82027,A0A0M6ZLI4,13-175,163,DGGDAVDLGQAPADILFLSAADTELGSFSAAHSALGTDSASLRLAN...
3,MC82027,A0A1X4ITI5,1-182,182,MHLLAATPGNLDDGLEPVDLGQSPADLVVLSAADTDLAALSEARNL...
4,MC82027,A0A1Q7WDG5,5-140,136,FVLLSTADTDLLAARASGAPWRVANPTRLGAADLPALLDGATLAVV...

In [ ]:
# The kernel Crached while executing code in the current cell, we skip the EDA
# Profiling Report
#profile_s = ProfileReport(df1, title="StandardDPCfam Metacluster Sequences - Exploratory Data Analysis", explorative=True)
#path_to_report = "/u/mdmc/enyanduk/internship_areasciencepark/Notebooks/profiling_reports/dpcfam_standard_mc_sequences_report.html"
#profile_s.to_file(path_to_report)
#profile_s

In [4]:
# DPCFamB Mcs Sequences
df2 = pd.read_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/DPCFamB/dpcfamB_sequences.csv")
df2.head()

,mcid,protein_id,seq_range,seq_length,aa_seq
0,MC113651,A0A0K6GCJ4,2-376,375,PTVVSSRALVPIGRRIRNAPEDSDASKAIVLRRKQQGETEDLSKAL...
1,MC113651,A8N621,40-384,345,TRALILRNGKHGAMGTGEIIASNKITGREKLDLLAEELIEKMKTAV...
2,MC113651,A0A0H2RRJ7,98-399,302,SNAVRAPFDLDSLIRWSQSQMDAALDQVNNLHETDFCYEIVERHIS...
3,MC113651,G4TJX7,26-369,344,VILSNQRREFVNTSSNAIALRYEPHGIWGEGQLASFKKRSGQEKLA...
4,MC113651,UPI0004449C2E,4-413,410,PPKDSKQPKDAPASTSRDLVRVGPRHVSAKHVVGRRNEDGQKPTTA...

In [5]:
# Profiling Report
profile_b = ProfileReport(df2, title="DPCfamB Metacluster Sequences - Exploratory Data Analysis", explorative=True)
path_to_report = "/u/mdmc/enyanduk/internship_areasciencepark/Notebooks/profiling_reports/dpcfam_b_mc_sequences_report.html"
profile_b.to_file(path_to_report)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:35<00:00,  7.08s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
profile_b

In [7]:
# We concatenate the two dataframes
df = pd.concat([df1, df2], ignore_index=True).drop_duplicates().reset_index(drop=True)
df.head()

,mcid,protein_id,seq_range,seq_length,aa_seq
0,MC82027,E8W9U6,2-131,130,ILLLSTSDTDLLSARAAQGPVSYRYANPSRLSLDALPQLLEGTDLV...
1,MC82027,I7DYJ9,1-143,143,MHVVFRESHGLDESDTPQDLGQTPADLVVLSFSDSDLGAFAAGWHR...
2,MC82027,A0A0M6ZLI4,13-175,163,DGGDAVDLGQAPADILFLSAADTELGSFSAAHSALGTDSASLRLAN...
3,MC82027,A0A1X4ITI5,1-182,182,MHLLAATPGNLDDGLEPVDLGQSPADLVVLSAADTDLAALSEARNL...
4,MC82027,A0A1Q7WDG5,5-140,136,FVLLSTADTDLLAARASGAPWRVANPTRLGAADLPALLDGATLAVV...

In [8]:
# In mcid column,we have values like MCID where ID is an integer. We wanna sort the dataframe based on ID in ascending order
# We can extract the integer part from the mcid column and sort the dataframe based on that
df["mcid_int"] = df["mcid"].str.extract(r"MC(\d+)").astype(int)
df = df.sort_values(by="mcid_int").reset_index(drop=True)
# We can drop the mcid_int column as we don't need it anymore
df = df.drop(columns=["mcid_int"])
df.head()

,mcid,protein_id,seq_range,seq_length,aa_seq
0,MC1,B0C3J8,589-773,185,FRSLYSQLHLLNPDLPISSLVISSCSPQEGKSTTSMHLAQAAAAMG...
1,MC1,I4CCA7,496-701,206,LTNAFRNIQTSISFVVEDSDMKTWVLSSAIPQEGKSFVSMSLAFTY...
2,MC1,A0A0K2GDM9,61-257,197,YRTLGLMLEQRRQTGLLQVVAMTSPTMGDGKTLTAINLAGAVSQSP...
3,MC1,A0A1R3X2Q7,585-760,176,SIRINLQYLMSETDFKVVGVTSSVSGEGKTFTSVNLSSEMAMAGKR...
4,MC1,A0A084U454,6-185,180,IIGVVNNKGGVLKTTLSTNLGACLSLDSKKTIIVDLDGQGNVIATF...

In [9]:
# Infos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16602778 entries, 0 to 16602777
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   mcid        object
 1   protein_id  object
 2   seq_range   object
 3   seq_length  int64
 4   aa_seq      object
dtypes: int64(1), object(4)
memory usage: 633.3+ MB

In [10]:
# How many unique mcids do we have?
print("Number of unique mcids:", df["mcid"].nunique())
# How many unique protein_ids do we have?
print("Number of unique protein_ids:", df["protein_id"].nunique())
# How many unique sequences do we have?
print("Number of unique sequences:", df["aa_seq"].nunique())

Number of unique mcids: 81384
Number of unique protein_ids: 10540602
Number of unique sequences: 16400721

In [11]:
# The Kernel crashed while executing code in the current cell 
# Profiling Report
#profile = ProfileReport(df, title="DPCfam Metacluster Sequences - Exploratory Data Analysis", explorative=True)
#path_to_report = "/u/mdmc/enyanduk/internship_areasciencepark/Notebooks/profiling_reports/dpcfam_metacluster_sequences_report.html"
#profile.to_file(path_to_report)

In [12]:
# Save the dataframe to csv file
df.to_csv("/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/Merged/dpcfam_all_mcs_sequences.csv", index=False)