**Goal**: Concatenate all dataframes related to DPCFam Standard MC properties into a single, consistent dataframe.

In [1]:
# 0. Imports
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import data_profiling # updated version of pandas-profiling
from data_profiling import ProfileReport

# I. Concatenating DataFrames

In [2]:
# 1. Paths to files
root_path = "/u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam"

# List of files to merge
files = [
    "mclist.csv",
    "sequence_information.csv",
    "pfam_comparison.csv",
    "lcregions.csv",
    "ccregions.csv",
    "disregions.csv",
    "tmregions.csv"
]

# Load all files into a list of DataFrames
dfs = [pd.read_csv(os.path.join(root_path, f)) for f in files]

In [3]:
# Merge all dataframes:
df = (
    pd.concat(
        [d.set_index("MCID") for d in dfs],
        axis=1,
        join="outer"  # keeps all MCIDs
    )
    .reset_index()
 )

In [4]:
df.head()

,MCID,seed_size,average_lenght,std_average_length,DA,DAC,%DA,%DAC,%DACF,%DACFA,AvOv,fred,fext,LABEL,pfam_seqs,%LC,%CC,%DIS,TM
0,1,17931,185.6810,28.76910,PF13614,CCL0023,0.442271,0.855137,0.989872,0.999022,0.808203,0.058723,0.134096,equivalent,6332,0.047194,0.000000,0.184394,0.009800
1,4,617,59.9109,6.06690,PF03600,CCL0182,0.628415,0.704918,0.970856,1.000000,0.075365,0.917423,0.699776,shifted,345,0.049879,0.000000,0.018654,1.261900
2,15,139,81.2086,5.05150,UNK,UNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131,0.049560,0.001799,0.138066,0.029126
3,19,120,71.5667,7.69711,PF11915,PF11915,0.940678,0.940678,1.000000,1.000000,0.136637,0.774788,0.722817,shifted,111,0.088535,0.022461,0.048627,1.689660
4,21,937,91.1974,7.69776,PF01012,CCL0039,0.988998,0.988998,1.000000,1.000000,0.345184,0.591957,0.278153,shifted,809,0.026462,0.000000,0.243835,0.000000

In [5]:
# Drop some useless columns
df = df.drop(columns=["DAC", "%DAC", "%DACF", "%DACFA", "fred", "fext","pfam_seqs"])

In [6]:
# New dataframe
df.head()

,MCID,seed_size,average_lenght,std_average_length,DA,%DA,AvOv,LABEL,%LC,%CC,%DIS,TM
0,1,17931,185.6810,28.76910,PF13614,0.442271,0.808203,equivalent,0.047194,0.000000,0.184394,0.009800
1,4,617,59.9109,6.06690,PF03600,0.628415,0.075365,shifted,0.049879,0.000000,0.018654,1.261900
2,15,139,81.2086,5.05150,UNK,NaN,NaN,NaN,0.049560,0.001799,0.138066,0.029126
3,19,120,71.5667,7.69711,PF11915,0.940678,0.136637,shifted,0.088535,0.022461,0.048627,1.689660
4,21,937,91.1974,7.69776,PF01012,0.988998,0.345184,shifted,0.026462,0.000000,0.243835,0.000000

In [7]:
# Rearrange columns properly
df = df[[
    "MCID", "seed_size", "average_lenght", "std_average_length", "%LC", "%CC", "%DIS", "TM", "DA", "%DA", "AvOv", "LABEL"
    ]]
df.head()

,MCID,seed_size,average_lenght,std_average_length,%LC,%CC,%DIS,TM,DA,%DA,AvOv,LABEL
0,1,17931,185.6810,28.76910,0.047194,0.000000,0.184394,0.009800,PF13614,0.442271,0.808203,equivalent
1,4,617,59.9109,6.06690,0.049879,0.000000,0.018654,1.261900,PF03600,0.628415,0.075365,shifted
2,15,139,81.2086,5.05150,0.049560,0.001799,0.138066,0.029126,UNK,NaN,NaN,NaN
3,19,120,71.5667,7.69711,0.088535,0.022461,0.048627,1.689660,PF11915,0.940678,0.136637,shifted
4,21,937,91.1974,7.69776,0.026462,0.000000,0.243835,0.000000,PF01012,0.988998,0.345184,shifted

In [8]:
# We rename columns properly to avoid conflicts in PostgreSQL:
df = df.rename(columns={
    "MCID": "mcid",
    "seed_size": "size_uniref50",
    "average_lenght": "avg_len",
    "std_average_length": "std_avg_len",
    "%LC": "lc_percent",
    "%CC": "cc_percent",
    "%DIS": "dis_percent",
    "TM": "tm",
    "DA": "pfam_da",
    "%DA": "da_percent",
    "AvOv": "avg_ov_percent",
    "LABEL": "overlap_label"
})
df.head()

,mcid,size_uniref50,avg_len,std_avg_len,lc_percent,cc_percent,dis_percent,tm,pfam_da,da_percent,avg_ov_percent,overlap_label
0,1,17931,185.6810,28.76910,0.047194,0.000000,0.184394,0.009800,PF13614,0.442271,0.808203,equivalent
1,4,617,59.9109,6.06690,0.049879,0.000000,0.018654,1.261900,PF03600,0.628415,0.075365,shifted
2,15,139,81.2086,5.05150,0.049560,0.001799,0.138066,0.029126,UNK,NaN,NaN,NaN
3,19,120,71.5667,7.69711,0.088535,0.022461,0.048627,1.689660,PF11915,0.940678,0.136637,shifted
4,21,937,91.1974,7.69776,0.026462,0.000000,0.243835,0.000000,PF01012,0.988998,0.345184,shifted

In [9]:
# We perform some meaningful transformations to make the data more interpretable:

# T1: Rewrite each ID in mcid column as MCID: e.g.: 1 -> MC1
df["mcid"] = "MC" + df["mcid"].astype(str)

# T2: The size_uniref50 column stores integer values. We convert them to the int type:
df["size_uniref50"] = df["size_uniref50"].astype(int)

# T3: For each value != NaN in cols, multiply it by 100 and round it
percent_cols = ["lc_percent", "cc_percent", "dis_percent", "da_percent", "avg_ov_percent"]
df[percent_cols] = df[percent_cols].fillna(0).mul(100).round(2)

# T4: Round specific cols to 2 digits:
round_cols = ["avg_len", "std_avg_len", "tm"]
df[round_cols] = df[round_cols].round(2)

# T5: In column pfam_da: replace UNK by UNKNOWN, in overlap_label: replace NaN by NONE
df["pfam_da"] = df["pfam_da"].replace("UNK", "UNKNOWN")
df["overlap_label"] = df["overlap_label"].str.capitalize().fillna("NONE")
df.head()

,mcid,size_uniref50,avg_len,std_avg_len,lc_percent,cc_percent,dis_percent,tm,pfam_da,da_percent,avg_ov_percent,overlap_label
0,MC1,17931,185.68,28.77,4.72,0.00,18.44,0.01,PF13614,44.23,80.82,Equivalent
1,MC4,617,59.91,6.07,4.99,0.00,1.87,1.26,PF03600,62.84,7.54,Shifted
2,MC15,139,81.21,5.05,4.96,0.18,13.81,0.03,UNKNOWN,0.00,0.00,NONE
3,MC19,120,71.57,7.70,8.85,2.25,4.86,1.69,PF11915,94.07,13.66,Shifted
4,MC21,937,91.20,7.70,2.65,0.00,24.38,0.00,PF01012,98.90,34.52,Shifted

In [10]:
# Infos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46828 entries, 0 to 46827
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mcid            46828 non-null  object
 1   size_uniref50   46828 non-null  int64
 2   avg_len         46828 non-null  float64
 3   std_avg_len     46828 non-null  float64
 4   lc_percent      46828 non-null  float64
 5   cc_percent      46828 non-null  float64
 6   dis_percent     46828 non-null  float64
 7   tm              46828 non-null  float64
 8   pfam_da         46828 non-null  object
 9   da_percent      46828 non-null  float64
 10  avg_ov_percent  46828 non-null  float64
 11  overlap_label   46828 non-null  object
dtypes: float64(8), int64(1), object(3)
memory usage: 4.3+ MB

In [11]:
# Statistics
df.describe().T

,count,mean,std,min,25%,50%,75%,max
size_uniref50,46828.0,328.904758,2146.797795,50.00,69.00,104.000,196.0000,131827.00
avg_len,46828.0,175.568361,162.883216,50.00,79.41,120.960,208.3250,3150.42
std_avg_len,46828.0,22.761171,25.212310,0.13,8.47,14.300,27.1700,544.91
lc_percent,46828.0,4.425717,4.629315,0.00,1.51,2.850,5.6000,49.97
cc_percent,46828.0,1.580738,7.391210,0.00,0.00,0.000,0.0200,86.34
dis_percent,46828.0,24.050744,14.235749,0.09,14.89,21.820,30.3200,92.85
tm,46828.0,0.348141,1.163270,0.00,0.00,0.000,0.0400,35.25
da_percent,46828.0,46.016375,43.294262,0.00,0.00,43.900,94.4400,100.00
avg_ov_percent,46828.0,30.051564,31.305588,0.00,0.00,21.335,49.9425,99.56

# II. Pfam Annotation Check

In [12]:
# Create a subdataframe df2 where pfam_da is "UNKNOWN"
df2 = df[df["pfam_da"] == "UNKNOWN"]
df2.head()

,mcid,size_uniref50,avg_len,std_avg_len,lc_percent,cc_percent,dis_percent,tm,pfam_da,da_percent,avg_ov_percent,overlap_label
2,MC15,139,81.21,5.05,4.96,0.18,13.81,0.03,UNKNOWN,0.0,0.0,NONE
12,MC73,76,153.57,20.28,0.78,0.00,14.82,0.00,UNKNOWN,0.0,0.0,NONE
13,MC77,118,60.57,10.56,1.57,0.00,34.78,0.00,UNKNOWN,0.0,0.0,NONE
14,MC82,59,191.24,25.70,6.79,0.00,6.72,0.00,UNKNOWN,0.0,0.0,NONE
18,MC100,81,107.57,13.13,0.62,0.00,17.40,0.00,UNKNOWN,0.0,0.0,NONE

In [13]:
# Check whether every time pfam_da is "UNKNOWN", da_percent and avg_ov_percent are 0, and overlap_label is "NONE"
condition = (df2["pfam_da"] == "UNKNOWN") & (df2["da_percent"] == 0) & (df2["avg_ov_percent"] == 0) & (df2["overlap_label"] == "NONE")
if condition.all():
    print("Every time pfam_da is 'UNKNOWN', da_percent and avg_ov_percent are 0, and overlap_label is 'NONE'.")
else:
    print("There are cases where pfam_da is 'UNKNOWN', but da_percent, avg_ov_percent, and overlap_label do not match the expected values.")

Every time pfam_da is 'UNKNOWN', da_percent and avg_ov_percent are 0, and overlap_label is 'NONE'.

**Conclusion**: `We will use the condition verified above, which reflects the reality of the original paper, and will help us fix errors in DPCFamB.`

# III. Data Profiling Report

In [14]:
# Profiling the dataset
profile = ProfileReport(df, title="DPCFam Standard Metacluster Properties Profiling Report", explorative=True)

# Generate path using os logic
report_dir = "/u/mdmc/enyanduk/internship_areasciencepark/Notebooks/profiling_reports"
os.makedirs(report_dir, exist_ok=True)
path_to_report = os.path.join(report_dir, "dpcfam_standard_mcs_properties_report.html")
profile.to_file(path_to_report)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:00<00:00, 40.96it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [15]:
profile

# IV. Save the Dataframe

In [16]:
# Save to csv
final_target = os.path.join(root_path, "dpcfam_standard_mcs_properties.csv")
df.to_csv(final_target, index=False)
print(f"Dataframe successfully saved to: {final_target}")

Dataframe successfully saved to: /u/mdmc/enyanduk/internship_areasciencepark/Dataframes/DPCFam/dpcfam_standard_mcs_properties.csv